const companiesData = {
  companiesListing: {
    data: {
      companies: [
        {
          id: 1,
          hsId: 'HSID 0',
          name: 'Company  0',
          ownerName: 'Stark Industries 0',
          createDate: '2022-09-29T07:44:20.447Z',
          phoneNumber: '+1234567890',
          lastActivityDate: '2023-02-17T07:44:20.447Z',
          industry: 'Accounting',
        },
        {
          id: 2,
          hsId: 'HSID 1',
          name: 'Company  1',
          ownerName: 'Stark Industries 1',
          createDate: '2023-05-22T07:44:20.481Z',
          phoneNumber: '+1234567890',
          lastActivityDate: '2023-06-23T07:44:20.481Z',
          industry: 'Alternative Medicine',
        },
        {
          id: 3,
          hsId: 'HSID 2',
          name: 'Company  2',
          ownerName: 'Stark Industries 2',
          createDate: '2023-07-17T07:44:20.486Z',
          phoneNumber: '+1234567890',
          lastActivityDate: '2022-09-22T07:44:20.485Z',
          industry: 'Airlines Aviation',
        },
      ],
    },
    pagination: {
      currentPage: 1,
      nextPage: 2,
      prevPage: null,
      totalPages: 10,
      totalCount: 100,
    },
    message: 'success',
    statusCode: 200,
  },

  statesData: {
    data: {
      states: {
        1: 'Punjab',
        2: 'Alaska',
        3: 'Alabama',
        4: 'Arkansas',
        5: 'Arizona',
        6: 'California',
        7: 'Colorado',
        8: 'Connecticut',
        9: 'District of Columbia',
      },
    },
    pagination: {},
    message: 'success',
  },
  industryVerticals: {
    data: {
      industryVerticals: {
        0: 'Accounting',
        1: 'Airlines Aviation',
        2: 'Alternative Dispute Resolution',
        3: 'Alternative Medicine',
        4: 'Animation',
        5: 'Apparel Fashion',
        6: 'Architecture Planning',
        7: 'Arts And Crafts',
        8: 'Automotive',
      },
    },
    pagination: {},
    message: 'success',
    statusCode: 200,
  },
  yearlyData: {
    data: {
      stats: {
        months: [
          'Oct 2022',
          'Nov 2022',
          'Dec 2022',
          'Jan 2023',
          'Feb 2023',
          'Mar 2023',
          'Apr 2023',
          'May 2023',
          'Jun 2023',
          'Jul 2023',
          'Aug 2023',
          'Sep 2023',
        ],
        values: [12, 10, 4, 6, 7, 7, 8, 13, 9, 8, 7, 3],
      },
    },
    message: 'success',
    statusCode: 200,
  },
  notesResponse: {
    data: {
      id: 9,
      notableType: 'Company',
      notableId: 1,
      title: 'html note',
      description: '"<ol><li>sdfsd</li><li>sdfsdfsdf</li></ol>"',
      userId: null,
    },
    message: 'success',
  },
  activities: {
    data: {
      activities: [
        {
          month: 'September, 2023',
          monthlyActivities: [
            {
              id: 9,
              title: 'Note Deleted',
              description: 'Note title',
              createdAt: '2023-09-14T12:49:34.163Z',
              userId: null,
            },
            {
              id: 8,
              title: 'Note Created',
              description: 'Note title',
              createdAt: '2023-09-14T12:39:25.584Z',
              userId: null,
            },
          ],
        },
      ],
    },
    message: 'success',
    statusCode: 200,
  },
  companyNotes: {
    data: {
      notes: [
        {
          month: 'September, 2023',
          monthlyNotes: [
            {
              id: 17,
              notableType: 'Company',
              notableId: 1,
              title: 'sdfsdf',
              description: '\u003cp\u003esdfsf\u003c/p\u003e',
              userId: null,
            },
            {
              id: 16,
              notableType: 'Company',
              notableId: 1,
              title: 'dsfsdfsdf',
              description: '\u003cp\u003edsfsdf\u003c/p\u003e',
              userId: null,
            },
          ],
        },
      ],
    },
    message: 'success',
    statusCode: 200,
  },
  companyDetail: {
    data: {
      company: {
        id: 1,
        hsId: 'HSID 0',
        name: 'Company 0',
        ownerName: 'Stark Industries 0',
        createDate: '2023-07-07T13:23:02.158Z',
        phoneNumber: '+1234567890',
        lastActivityDate: '2023-06-07T13:23:02.158Z',
        industry: 'Industry 8',
        parentCompany: null,
      },
      notes: [
        {
          firstName: 'John',
          lastName: 'Doe2',
          email: 'john.doe2@example.com',
          jobTitle: 'Sales person 2',
          phoneNumber: '+1234567890',
        },
        {
          firstName: 'John',
          lastName: 'Doe14',
          email: 'john.doe14@example.com',
          jobTitle: 'Sales person 14',
          phoneNumber: '+1234567890',
        },
        {
          firstName: 'John',
          lastName: 'Doe24',
          email: 'john.doe24@example.com',
          jobTitle: 'Sales person 24',
          phoneNumber: '+1234567890',
        },
        {
          firstName: 'John',
          lastName: 'Doe25',
          email: 'john.doe25@example.com',
          jobTitle: 'Sales person 25',
          phoneNumber: '+1234567890',
        },
        {
          firstName: 'John',
          lastName: 'Doe26',
          email: 'john.doe26@example.com',
          jobTitle: 'Sales person 26',
          phoneNumber: '+1234567890',
        },
        {
          firstName: 'John',
          lastName: 'Doe30',
          email: 'john.doe30@example.com',
          jobTitle: 'Sales person 30',
          phoneNumber: '+1234567890',
        },
        {
          firstName: 'John',
          lastName: 'Doe40',
          email: 'john.doe40@example.com',
          jobTitle: 'Sales person 40',
          phoneNumber: '+1234567890',
        },
        {
          firstName: 'John',
          lastName: 'Doe41',
          email: 'john.doe41@example.com',
          jobTitle: 'Sales person 41',
          phoneNumber: '+1234567890',
        },
        {
          firstName: 'John',
          lastName: 'Doe46',
          email: 'john.doe46@example.com',
          jobTitle: 'Sales person 46',
          phoneNumber: '+1234567890',
        },
        {
          firstName: 'John',
          lastName: 'Doe61',
          email: 'john.doe61@example.com',
          jobTitle: 'Sales person 61',
          phoneNumber: '+1234567890',
        },
        {
          firstName: 'John',
          lastName: 'Doe80',
          email: 'john.doe80@example.com',
          jobTitle: 'Sales person 80',
          phoneNumber: '+1234567890',
        },
        {
          firstName: 'John',
          lastName: 'Doe85',
          email: 'john.doe85@example.com',
          jobTitle: 'Sales person 85',
          phoneNumber: '+1234567890',
        },
        {
          firstName: 'John',
          lastName: 'Doe86',
          email: 'john.doe86@example.com',
          jobTitle: 'Sales person 86',
          phoneNumber: '+1234567890',
        },
        {
          firstName: 'John',
          lastName: 'Doe89',
          email: 'john.doe89@example.com',
          jobTitle: 'Sales person 89',
          phoneNumber: '+1234567890',
        },
        {
          firstName: 'John',
          lastName: 'Doe91',
          email: 'john.doe91@example.com',
          jobTitle: 'Sales person 91',
          phoneNumber: '+1234567890',
        },
        {
          firstName: 'John',
          lastName: 'Doe93',
          email: 'john.doe93@example.com',
          jobTitle: 'Sales person 93',
          phoneNumber: '+1234567890',
        },
        {
          firstName: 'John',
          lastName: 'Doe98',
          email: 'john.doe98@example.com',
          jobTitle: 'Sales person 98',
          phoneNumber: '+1234567890',
        },
      ],
      deals: [
        {
          description: 'Dedicated Armed Officers',
          totalCost: 6065.3,
          date: '2023-09-01',
          stage: 'Proposing',
        },
      ],
    },
    message: 'success',
    statusCode: 200,
  },
  createCompanyNote: {
    data: {
      id: 15,
      notableType: 'Company',
      notableId: 1,
      title: 'Title testing',
      description: '<p>description testing</p>',
      userId: null,
    },
    message: 'success',
    statusCode: 200,
  },
  deleteCompanyNote: {
    message: 'success',
    statusCode: 200,
  },
  dashboarProposalWon: {
    data: {
      proposalWon: [
        {
          location: '',
          proposalDate: '2024-05-04T15:54:11Z',
          amount: 1.01,
          terms: 'weekly',
          ownerName: 'Areeba Khalil',
        },
        {
          location: 'Eagle Village Reichert Flats',
          proposalDate: '2024-05-03T13:45:17Z',
          amount: 1.1,
          terms: 'weekly',
          ownerName: 'AZAZ',
        },
        {
          location: '',
          proposalDate: '2024-05-03T14:38:09Z',
          amount: 1.01,
          terms: 'weekly',
          ownerName: 'AZAZ',
        },
        {
          location: 'Summer Acres Diamond Plaza',
          proposalDate: '2024-05-04T16:04:05Z',
          amount: 1.01,
          terms: 'weekly',
          ownerName: 'Hamza Imran',
        },
        {
          location: 'Royal Pointe Cummerata Tunnel',
          proposalDate: '2024-05-04T16:21:08Z',
          amount: 1.01,
          terms: 'weekly',
          ownerName: 'Hamza Imran',
        },
      ],
    },
    pagination: {
      currentPage: 1,
      nextPage: 2,
      prevPage: null,
      totalPages: 16,
      totalCount: 79,
    },
    statusCode: 200,
    message: 'success',
  },
  dashboardProposalLost: {
    data: {
      proposalLost: [
        {
          location: 'Autumn Court Alton Ports',
          proposalDate: '2024-05-02T14:52:47Z',
          amount: 0,
          terms: 'weekly',
          ownerName: 'tahniyat kazmi',
        },
        {
          location: 'Limoncello Miami',
          proposalDate: '2024-05-04T13:28:28Z',
          amount: 0,
          terms: 'weekly',
          ownerName: 'AZAZ',
        },
        {
          location: '',
          proposalDate: '2024-05-04T14:31:48Z',
          amount: 5570.25,
          terms: 'weekly',
          ownerName: 'AZAZ',
        },
      ],
    },
    pagination: {
      currentPage: 1,
      nextPage: null,
      prevPage: null,
      totalPages: 1,
      totalCount: 3,
    },
    statusCode: 200,
    message: 'success',
  },
  companiesOption: {
    data: {
      companies: [
        {
          id: 1168,
          name: "'zain hacked it",
          parentCompanyId: null,
          parentCompanyName: null,
        },
        {
          id: 1166,
          name: "'zain hacked it",
          parentCompanyId: null,
          parentCompanyName: null,
        },
        {
          id: 1169,
          name: '<h2>zain hacked it',
          parentCompanyId: null,
          parentCompanyName: null,
        },
        {
          id: 1172,
          name: '<h2>zain hacked it',
          parentCompanyId: null,
          parentCompanyName: null,
        },
        {
          id: 1171,
          name: '<h2>zain hacked it',
          parentCompanyId: null,
          parentCompanyName: null,
        },
        {
          id: 1174,
          name: '<h2>zain hacked it',
          parentCompanyId: null,
          parentCompanyName: null,
        },
        {
          id: 806,
          name: 'Abbott and Sons',
          parentCompanyId: 373,
          parentCompanyName: 'Flatley, Huel and Smitham',
        },
        {
          id: 53,
          name: 'Abbott LLC',
          parentCompanyId: 1030,
          parentCompanyName: 'Hand-Spencer',
        },
        {
          id: 860,
          name: 'Abbott, Hettinger and Jones',
          parentCompanyId: 512,
          parentCompanyName: 'Robel, Lueilwitz and Ryan',
        },
        {
          id: 188,
          name: 'Abbott, Nienow and Hyatt',
          parentCompanyId: 491,
          parentCompanyName: 'Ondricka Group',
        },
      ],
      pagination: {
        currentPage: 1,
        nextPage: 2,
        prevPage: null,
        totalPages: 209,
        totalCount: 150,
      },
    },
    statusCode: 200,
    message: 'success',
  },
};

export default companiesData;
