import { SCHEDULE_STATS_FOOTER_VARIANTS } from '../components/scheduleStatsFooter';

/** @deprecated Prefer getScheduleHeaderTabs — static labels ignore tenant config. */
export const SCHEDULE_HEADER_TABS = [
  { id: 'overview', label: 'Overview' },
  // TODO: temporarily hidden — restore when Officer tab is ready
  // { id: 'officer', label: 'Officer' },
  { id: 'dedicated', label: 'Dedicated' },
  { id: 'patrol', label: 'Patrol' },
];

/**
 * True when the tenant sells exactly one schedulable service. For those tenants
 * Overview and the single service tab render the same grid from the same call,
 * so showing both is pure duplication.
 */
export const isSingleServiceTenant = (services = {}) =>
  [services?.patrol === true, services?.dedicated === true].filter(Boolean).length === 1;

/**
 * Schedule header tabs driven by tenant services + tenant labels.
 *
 * Multi-service tenants get Overview (cross-service roll-up) plus a tab per
 * service. Single-service tenants get one tab, named for their service and
 * backed by the Overview config — it keeps the coverage/KPI footer, which the
 * per-service tabs do not fetch, and drops the duplicate.
 */
export const getScheduleHeaderTabs = ({
  services = {},
  getLabel,
  t,
  shiftTypes = {},
  includeOfficerTab = false,
  /* The scheduler moves the company reading onto its grouping tab row, so the header
     row must be able to omit the Companies *tab*. Defaults to *true* so any other
     caller keeps it — `SCHEDULE_TAB_CONFIGS.companies` is still what mounts the
     pane either way. */
  includeCompaniesTab = true,
} = {}) => {
  const resolveTerm = (key, fallback) => {
    const fromShiftTypes =
      shiftTypes?.[key]?.label || (typeof shiftTypes?.[key] === 'string' ? shiftTypes[key] : '');
    const fromTerms = getLabel?.('terms', key, t);
    return fromShiftTypes || fromTerms || fallback;
  };

  /**
   * The Visits tab is **retired from the tab row**, not deleted.
   *
   * Visits are now reached two ways, both better than a tab of their own: the
   * main service tab switches its left column to companies and draws the visits
   * themselves (see `MAIN_VIEW_GROUPING`), and the Companies tab holds the
   * grouped, cross-week view. A third surface listing the same visits by site
   * was the odd one out — it grouped by the one thing neither planner question
   * starts from.
   *
   * The config below is still live: the grid, the harmonize CTA and the visit
   * drawer all read `visits` behaviour through it, and the main view's company
   * grouping runs on the same `apiView`. Only the tab button is gone.
   */
  const companiesTab = {
    id: COMPANIES_SCHEDULE_TAB_ID,
    label: t?.('obx.schedules.calendar.tabs.companies') || 'Companies',
  };

  if (isSingleServiceTenant(services)) {
    const serviceKey = services?.patrol === true ? 'patrol' : 'dedicated';
    const tabs = [
      {
        id: 'overview',
        label: resolveTerm(serviceKey, serviceKey === 'patrol' ? 'Patrol' : 'Dedicated'),
      },
    ];

    if (services?.patrol === true && includeCompaniesTab) {
      tabs.push(companiesTab);
    }
    return tabs;
  }

  const tabs = [
    { id: 'overview', label: t?.('obx.schedules.calendar.tabs.overview') || 'Overview' },
  ];

  // Officer tab stays opt-in until the view is ready for all tenants.
  if (includeOfficerTab) {
    tabs.push({ id: 'officer', label: resolveTerm('officer', 'Officer') });
  }

  if (services?.dedicated === true) {
    tabs.push({ id: 'dedicated', label: resolveTerm('dedicated', 'Dedicated') });
  }

  if (services?.patrol === true) {
    tabs.push({ id: 'patrol', label: resolveTerm('patrol', 'Patrol') });
    // Visits are demand generated by the patrol/filter-replacement service, so
    // the tab only makes sense where that service is sold.
    if (includeCompaniesTab) {
      tabs.push(companiesTab);
    }
  }

  return tabs;
};

/** @deprecated Prefer getOverviewSections */
export const OVERVIEW_SECTIONS = [
  {
    id: 'overview-patrol',
    type: 'accordion-section',
    title: 'Patrol Shifts',
    rows: [],
  },
  {
    id: 'overview-dedicated',
    type: 'accordion-section',
    title: 'Dedicated Shifts',
    rows: [],
  },
];

const resolveDutyTerm = (key, fallback, { getLabel, t, shiftTypes = {} } = {}) => {
  const fromShiftTypes =
    shiftTypes?.[key]?.label || (typeof shiftTypes?.[key] === 'string' ? shiftTypes[key] : '');
  const fromTerms = getLabel?.('terms', key, t);
  return fromShiftTypes || fromTerms || fallback;
};

/**
 * Remap API day/week section titles (e.g. "Patrol Runsheets") to tenant labels.
 */
export const resolveScheduleSectionTitle = (title, { getLabel, t, shiftTypes = {} } = {}) => {
  if (!title) return title;

  const patrol = resolveDutyTerm('patrol', 'Patrol', { getLabel, t, shiftTypes });
  const dedicated = resolveDutyTerm('dedicated', 'Dedicated', { getLabel, t, shiftTypes });
  const runsheets = getLabel?.('terms', 'runsheets', t) || 'Runsheets';
  const runsheet = getLabel?.('terms', 'runsheet', t) || 'Runsheet';

  const replacements = [
    [/Patrol\s+Runsheets/gi, `${patrol} ${runsheets}`],
    [/Patrol\s+Runsheet/gi, `${patrol} ${runsheet}`],
    [/Patrol\s+Shifts/gi, `${patrol} Shifts`],
    [/Patrol\s+Jobs/gi, `${patrol} Jobs`],
    [/Dedicated\s+Shifts/gi, `${dedicated} Shifts`],
    [/Dedicated\s+Duties/gi, `${dedicated} Duties`],
    [/Dedicated\s+Jobs/gi, `${dedicated} Jobs`],
    [/Dedicated\s+Runsheets/gi, `${dedicated} ${runsheets}`],
  ];

  return replacements.reduce(
    (result, [pattern, replacement]) => result.replace(pattern, replacement),
    String(title),
  );
};

export const getOverviewSections = ({ services = {}, getLabel, t, shiftTypes = {} } = {}) => {
  const resolveTerm = (key, fallback) =>
    resolveDutyTerm(key, fallback, { getLabel, t, shiftTypes });

  const sections = [];

  if (services?.patrol === true) {
    sections.push({
      id: 'overview-patrol',
      type: 'accordion-section',
      title: `${resolveTerm('patrol', 'Patrol')} Shifts`,
      rows: [],
    });
  }

  if (services?.dedicated === true) {
    sections.push({
      id: 'overview-dedicated',
      type: 'accordion-section',
      title: `${resolveTerm('dedicated', 'Dedicated')} Shifts`,
      rows: [],
    });
  }

  return sections;
};

/** Harmonize acts on visits, so it only exists on the visits tab. */
export const VISITS_SCHEDULE_TAB_ID = 'visits';

/**
 * The Companies tab is a **list**, not a calendar.
 *
 * Every other tab here is a variant of the same FullCalendar resource timeline,
 * so this one is the exception the render path has to branch on: it owns its own
 * pane, it has no `apiView` on the grid endpoint, and the Day/Week/Month switcher
 * is hidden because a rolling twelve months is not a FullCalendar view type.
 */
export const COMPANIES_SCHEDULE_TAB_ID = 'companies';

export const EMBEDDED_SCHEDULE_TAB_ID = 'embedded';

/** @deprecated Use EMBEDDED_SCHEDULE_TAB_ID */
export const SITE_SCHEDULE_TAB_ID = EMBEDDED_SCHEDULE_TAB_ID;

/** Shared shift-filter option sets. Omit / null on a tab to use DUTIES_FILTER_DATA. */
export const getDedicatedShiftTypeOptions = (t, getLabel, services = {}) => {
  const options = [
    {
      value: 'dedicated',
      label: t('obx.schedules.filters.duties.dedicated', {
        dedicated: getLabel?.('terms', 'dedicated', t) || 'Dedicated',
      }),
    },
    {
      value: 'extra',
      label: t('obx.schedules.filters.duties.extra', {
        extra: getLabel?.('terms', 'extra', t) || 'Extra',
      }),
    },
  ];

  if (services?.dispatch === true) {
    options.push({
      value: 'dispatch',
      label: t('obx.schedules.filters.duties.dispatch', {
        dispatch: getLabel?.('terms', 'dispatch', t) || 'Dispatch',
      }),
    });
  }

  options.push({
    value: 'overtime',
    label: t('obx.schedules.filters.duties.overtime'),
  });

  return options;
};

export const getPatrolShiftTypeOptions = (t, getLabel, services = {}) => {
  const options = [
    {
      value: 'patrol',
      label: t('obx.schedules.filters.duties.patrol', {
        patrol: getLabel?.('terms', 'patrol', t) || 'Patrol',
      }),
    },
  ];

  if (services?.dispatch === true) {
    options.push({
      value: 'dispatch',
      label: t('obx.schedules.filters.duties.dispatch', {
        dispatch: getLabel?.('terms', 'dispatch', t) || 'Dispatch',
      }),
    });
  }

  options.push({
    value: 'overtime',
    label: t('obx.schedules.filters.duties.overtime'),
  });

  return options;
};

/** @deprecated Use getDedicatedShiftTypeOptions */
export const DEDICATED_SHIFT_TYPE_OPTIONS = [
  { value: 'dedicated', label: 'Dedicated Shift' },
  { value: 'extra', label: 'Extra Job' },
  { value: 'dispatch', label: 'Dispatch' },
  { value: 'overtime', label: 'Overtime' },
];

/** @deprecated Use getPatrolShiftTypeOptions */
export const PATROL_SHIFT_TYPE_OPTIONS = [
  { value: 'patrol', label: 'Patrol Shift' },
  { value: 'dispatch', label: 'Dispatch' },
  { value: 'overtime', label: 'Overtime' },
];

/**
 * What the main service tab puts in its left column, and therefore what it draws
 * in the grid.
 *
 * `ROUTES` is the original view: one row per route, cards are the routes. In
 * `COMPANIES` the rows become the customers and the cards become the **visits** —
 * the same week, one level down. A route is a club of visits, so these are two
 * readings of one dataset rather than two datasets, which is why this is a
 * grouping switch on one tab and not a second tab.
 */
export const MAIN_VIEW_GROUPING = {
  ROUTES: 'routes',
  COMPANIES: 'companies',
};

/**
 * Only the tenant whose whole book is visits gets the grouping switch: on a
 * multi-service tenant the main tab is a cross-service roll-up whose rows are
 * already two different kinds of thing, and a company grouping there would have
 * to drop the dedicated half to mean anything.
 */
export const canGroupMainViewByCompany = ({ services = {}, tabConfig } = {}) =>
  Boolean(tabConfig?.isOverviewTab) && isSingleServiceTenant(services) && services?.patrol === true;

/**
 * Whether the things on screen are **visits** rather than shifts.
 *
 * Everything downstream that has to name the unit — the unrouted-demand pill, its
 * tooltip, the footer's status list — was keying off `isVisitsTab`, which is a
 * fact about the tab and not about the cards. The company grouping draws visits
 * from the main tab's config, so on that surface the tab flag says shifts while
 * the grid says visits, and the copy followed the flag.
 */
export const isVisitsSubject = ({ tabConfig, isCompanyGrouping = false } = {}) =>
  Boolean(tabConfig?.isVisitsTab) || Boolean(isCompanyGrouping);

/**
 * The main tab's config as the **company grouping** needs its filter row.
 *
 * `All Jobs` and `Locations` are questions about the routes reading: a job type
 * only distinguishes rows whose subject is a shift, and a location is a level
 * *below* the site — under a company row neither narrows anything the planner can
 * see, so they were two dropdowns that looked like they did something and did not.
 *
 * The technician dropdown goes with them, for a sharper reason: it *would* have
 * narrowed, and narrowed the wrong thing. Grouped by company the row is a customer
 * and the technician is a fact about the individual card, so picking one empties
 * whole company rows — the grid then says "this customer has no work this week"
 * when the truth is "this technician has none at this customer". A control that
 * turns one question into a different one is worse than a missing control.
 *
 * A grouping, not a tab, so this cannot be a flag on `SCHEDULE_TAB_CONFIGS.overview`
 * — the dedicated and patrol tabs and the multi-service overview share that config
 * and still need all three, and the routes grouping keeps the technician dropdown
 * (see `withRouteGroupingFilters`). The caller hands the result to the filter row
 * only; the fetch keeps reading the real config, and drops the same three
 * dimensions from the query so none of them can narrow the payload with no dropdown
 * left to clear it.
 */
export const withCompanyGroupingFilters = (tabConfig) => ({
  ...tabConfig,
  filters: {
    ...tabConfig?.filters,
    showShiftType: false,
    showLocation: false,
    showOfficer: false,
  },
});

/**
 * The main tab's config as the **routes grouping** needs its filter row — the
 * sibling of `withCompanyGroupingFilters`, and it drops two of the same three.
 *
 * `Locations` goes because on this tenant it is a level that does not exist as a
 * question. A route's rows are routes and its cards are visits, and a visit is one
 * service occurrence at one *site*; the location dimension below the site is a
 * dedicated-guarding idea (a post, a patrol point) that the visits book never
 * populates, so the dropdown offered a list the grid could not be narrowed by.
 * Note the week view was its only surface anyway — day and month already hide it,
 * because their fetches drop `locationId` — so this closes the one reading that
 * still showed a control the planner had nothing to do with.
 *
 * `All Jobs` goes for the reason the company grouping drops it, one step stronger:
 * the tenant that gets the grouping switch is single-service by definition
 * (`canGroupMainViewByCompany`), so *every* card on the tab is the same job type and
 * the dropdown's only two meaningful positions are "all" and "all". With the company
 * grouping already dropping it, this makes the job filter absent from **both**
 * readings of that tab — all three views — which is the honest end state: a question
 * with one answer is not a filter.
 *
 * The `showOfficer` dropdown **stays** — the row of installers, in this tenant's
 * words. It is the one of the three that still narrows the right thing here: the
 * rows are routes, a route has one person on it, and picking one selects routes
 * rather than emptying them. Unchanged on week; day and month drop it in the fetch
 * and hide it for the same reason they drop `Locations`.
 *
 * Derived per grouping for the same reason as its sibling — the main tab's config is
 * shared with tabs that ask all three questions — and the fetch drops `shiftType`
 * and `locationId` alongside it, so neither can keep narrowing the payload once its
 * control is gone.
 */
export const withRouteGroupingFilters = (tabConfig) => ({
  ...tabConfig,
  filters: {
    ...tabConfig?.filters,
    showShiftType: false,
    showLocation: false,
  },
});

export const RESOURCE_AREA_HEADER_KEYS = {
  OFFICERS: 'officers',
  LOCATIONS: 'locations',
  RUNSHEETS: 'runsheets',
  SITES: 'sites',
  COMPANIES: 'companies',
};

export const resolveResourceAreaHeader = (headerKey, getLabel, t) => {
  if (!headerKey) return '';

  if (headerKey === RESOURCE_AREA_HEADER_KEYS.OFFICERS) {
    return getLabel?.('terms', 'officers', t) || 'Officers';
  }
  if (headerKey === RESOURCE_AREA_HEADER_KEYS.RUNSHEETS) {
    return getLabel?.('terms', 'runsheets', t) || 'Runsheets';
  }
  if (headerKey === RESOURCE_AREA_HEADER_KEYS.LOCATIONS) {
    return t?.('obx.schedules.calendar.resourceHeaders.locations') || 'Locations';
  }
  if (headerKey === RESOURCE_AREA_HEADER_KEYS.SITES) {
    return getLabel?.('terms', 'sites', t) || 'Sites';
  }
  if (headerKey === RESOURCE_AREA_HEADER_KEYS.COMPANIES) {
    return t?.('obx.schedules.calendar.companies.companyColumn') || 'Company';
  }

  return '';
};

const DEFAULT_FILTERS = {
  showShiftType: true,
  showLocation: true,
  showOfficer: true,
  /** null | 'dedicated' | 'patrol' — resolved at render with getLabel */
  shiftTypeOptionsKey: null,
  patrolStatusOptions: false,
};

export const SCHEDULE_TAB_CONFIGS = {
  embedded: {
    id: EMBEDDED_SCHEDULE_TAB_ID,
    apiView: null,
    footerVariant: null,
    resourceAreaHeaderKey: null,
    isOverviewTab: false,
    isLegacyEmbeddedView: true,
    filters: {
      ...DEFAULT_FILTERS,
      showLocation: false,
      showOfficer: false,
    },
    requiresSiteLocations: false,
  },
  overview: {
    id: 'overview',
    // Week Overview fetches patrol + dedicated grids (no view=overview).
    // Coverage / top-row KPIs come from summary/stats; bottom row sums legends.
    apiView: null,
    footerVariant: SCHEDULE_STATS_FOOTER_VARIANTS.OVERVIEW,
    resourceAreaHeaderKey: null,
    isOverviewTab: true,
    filters: {
      ...DEFAULT_FILTERS,
    },
    requiresSiteLocations: false,
  },
  officer: {
    id: 'officer',
    apiView: 'officer',
    // Tall Overview stats (Coverage + 6 + 9) are Overview-tab only.
    footerVariant: null,
    resourceAreaHeaderKey: RESOURCE_AREA_HEADER_KEYS.OFFICERS,
    isOverviewTab: false,
    filters: {
      ...DEFAULT_FILTERS,
    },
    requiresSiteLocations: false,
  },
  dedicated: {
    id: 'dedicated',
    apiView: 'dedicated',
    footerVariant: SCHEDULE_STATS_FOOTER_VARIANTS.DEDICATED,
    resourceAreaHeaderKey: RESOURCE_AREA_HEADER_KEYS.LOCATIONS,
    isOverviewTab: false,
    filters: {
      ...DEFAULT_FILTERS,
      shiftTypeOptionsKey: 'dedicated',
    },
    requiresSiteLocations: false,
  },
  patrol: {
    id: 'patrol',
    apiView: 'patrol',
    footerVariant: SCHEDULE_STATS_FOOTER_VARIANTS.PATROL,
    resourceAreaHeaderKey: RESOURCE_AREA_HEADER_KEYS.RUNSHEETS,
    isOverviewTab: false,
    filters: {
      ...DEFAULT_FILTERS,
      showLocation: false,
      shiftTypeOptionsKey: 'patrol',
      patrolStatusOptions: true,
    },
    requiresSiteLocations: false,
  },
  /**
   * Visits (API: "hits") are the unit of demand — one service occurrence at one
   * site. Every other week view groups by something a visit must already belong
   * to (a runsheet, a location, an officer), so unassigned demand had no row and
   * could not be drawn at all. Here rows are sites, with unassigned demand
   * pinned above them, which is what makes the whole week visible in one place.
   */
  /**
   * Companies groups the same visits by the customer they belong to, and shows a
   * rolling year rather than a week. It is a sibling of `visits`, not a variant:
   * no `apiView` (it calls its own endpoint), no resource-area header, no footer
   * variant, and no shift-type or location filters — the rail and the search box
   * are the only narrowing this surface offers.
   */
  companies: {
    id: COMPANIES_SCHEDULE_TAB_ID,
    apiView: null,
    footerVariant: null,
    resourceAreaHeaderKey: null,
    isOverviewTab: false,
    isCompaniesTab: true,
    /** Owns its own pane, so the calendar fetch and the view switcher are skipped. */
    rendersOwnPane: true,
    filters: {
      ...DEFAULT_FILTERS,
      showShiftType: false,
      showLocation: false,
      showOfficer: false,
      shiftTypeOptionsKey: null,
      patrolStatusOptions: false,
    },
    requiresSiteLocations: false,
  },
  visits: {
    id: 'visits',
    apiView: 'visits',
    footerVariant: SCHEDULE_STATS_FOOTER_VARIANTS.VISITS,
    resourceAreaHeaderKey: RESOURCE_AREA_HEADER_KEYS.SITES,
    isOverviewTab: false,
    isVisitsTab: true,
    filters: {
      ...DEFAULT_FILTERS,
      showLocation: false,
      shiftTypeOptionsKey: null,
      showShiftType: false,
      patrolStatusOptions: true,
    },
    requiresSiteLocations: false,
  },
};

export const getScheduleTabConfig = (tabId) =>
  SCHEDULE_TAB_CONFIGS[tabId] || SCHEDULE_TAB_CONFIGS.overview;

export const getScheduleTabFooterVariant = (tabId) => getScheduleTabConfig(tabId).footerVariant;

/**
 * The footer variant for a tab **as it is currently grouped**.
 *
 * `footerVariant` is a property of the tab config, and the routes grouping shares
 * the main tab's config — so the company grouping inherited the overview footer.
 * That footer counts `Split`, a shift concept permanently 0 for visits, and counts
 * no missed or cancelled visits at all, which is why it summed to 6 of the 8
 * visits the week grid had drawn. Grouped by company the subject is visits, so the
 * visits variant is the honest one; it has to be resolved per grouping because the
 * tab id alone cannot tell the two readings apart.
 */
export const resolveScheduleFooterVariant = (tabId, { isCompanyGrouping = false } = {}) => {
  const tabConfig = getScheduleTabConfig(tabId);

  return isVisitsSubject({ tabConfig, isCompanyGrouping })
    ? SCHEDULE_STATS_FOOTER_VARIANTS.VISITS
    : tabConfig.footerVariant;
};
