import { SCHEDULE_STATS_FOOTER_VARIANTS } from '../components/scheduleStatsFooter';

/** @deprecated Prefer getScheduleHeaderTabs — static labels ignore tenant config. */
export const SCHEDULE_HEADER_TABS = [
  { id: 'overview', label: 'Overview' },
  // TODO: temporarily hidden — restore when Officer tab is ready
  // { id: 'officer', label: 'Officer' },
  { id: 'dedicated', label: 'Dedicated' },
  { id: 'patrol', label: 'Patrol' },
];

/**
 * True when the tenant sells exactly one schedulable service. For those tenants
 * Overview and the single service tab render the same grid from the same call,
 * so showing both is pure duplication.
 */
export const isSingleServiceTenant = (services = {}) =>
  [services?.patrol === true, services?.dedicated === true].filter(Boolean).length === 1;

/**
 * Schedule header tabs driven by tenant services + tenant labels.
 *
 * Multi-service tenants get Overview (cross-service roll-up) plus a tab per
 * service. Single-service tenants get one tab, named for their service and
 * backed by the Overview config — it keeps the coverage/KPI footer, which the
 * per-service tabs do not fetch, and drops the duplicate.
 */
export const getScheduleHeaderTabs = ({
  services = {},
  getLabel,
  t,
  shiftTypes = {},
  includeOfficerTab = false,
} = {}) => {
  const resolveTerm = (key, fallback) => {
    const fromShiftTypes =
      shiftTypes?.[key]?.label || (typeof shiftTypes?.[key] === 'string' ? shiftTypes[key] : '');
    const fromTerms = getLabel?.('terms', key, t);
    return fromShiftTypes || fromTerms || fallback;
  };

  const visitsTab = { id: 'visits', label: getLabel?.('terms', 'hits', t) || 'Visits' };

  if (isSingleServiceTenant(services)) {
    const serviceKey = services?.patrol === true ? 'patrol' : 'dedicated';
    const tabs = [
      {
        id: 'overview',
        label: resolveTerm(serviceKey, serviceKey === 'patrol' ? 'Patrol' : 'Dedicated'),
      },
    ];

    if (services?.patrol === true) tabs.push(visitsTab);
    return tabs;
  }

  const tabs = [
    { id: 'overview', label: t?.('obx.schedules.calendar.tabs.overview') || 'Overview' },
  ];

  // Officer tab stays opt-in until the view is ready for all tenants.
  if (includeOfficerTab) {
    tabs.push({ id: 'officer', label: resolveTerm('officer', 'Officer') });
  }

  if (services?.dedicated === true) {
    tabs.push({ id: 'dedicated', label: resolveTerm('dedicated', 'Dedicated') });
  }

  if (services?.patrol === true) {
    tabs.push({ id: 'patrol', label: resolveTerm('patrol', 'Patrol') });
    // Visits are demand generated by the patrol/filter-replacement service, so
    // the tab only makes sense where that service is sold.
    tabs.push(visitsTab);
  }

  return tabs;
};

/** @deprecated Prefer getOverviewSections */
export const OVERVIEW_SECTIONS = [
  {
    id: 'overview-patrol',
    type: 'accordion-section',
    title: 'Patrol Shifts',
    rows: [],
  },
  {
    id: 'overview-dedicated',
    type: 'accordion-section',
    title: 'Dedicated Shifts',
    rows: [],
  },
];

const resolveDutyTerm = (key, fallback, { getLabel, t, shiftTypes = {} } = {}) => {
  const fromShiftTypes =
    shiftTypes?.[key]?.label || (typeof shiftTypes?.[key] === 'string' ? shiftTypes[key] : '');
  const fromTerms = getLabel?.('terms', key, t);
  return fromShiftTypes || fromTerms || fallback;
};

/**
 * Remap API day/week section titles (e.g. "Patrol Runsheets") to tenant labels.
 */
export const resolveScheduleSectionTitle = (title, { getLabel, t, shiftTypes = {} } = {}) => {
  if (!title) return title;

  const patrol = resolveDutyTerm('patrol', 'Patrol', { getLabel, t, shiftTypes });
  const dedicated = resolveDutyTerm('dedicated', 'Dedicated', { getLabel, t, shiftTypes });
  const runsheets = getLabel?.('terms', 'runsheets', t) || 'Runsheets';
  const runsheet = getLabel?.('terms', 'runsheet', t) || 'Runsheet';

  const replacements = [
    [/Patrol\s+Runsheets/gi, `${patrol} ${runsheets}`],
    [/Patrol\s+Runsheet/gi, `${patrol} ${runsheet}`],
    [/Patrol\s+Shifts/gi, `${patrol} Shifts`],
    [/Patrol\s+Jobs/gi, `${patrol} Jobs`],
    [/Dedicated\s+Shifts/gi, `${dedicated} Shifts`],
    [/Dedicated\s+Duties/gi, `${dedicated} Duties`],
    [/Dedicated\s+Jobs/gi, `${dedicated} Jobs`],
    [/Dedicated\s+Runsheets/gi, `${dedicated} ${runsheets}`],
  ];

  return replacements.reduce(
    (result, [pattern, replacement]) => result.replace(pattern, replacement),
    String(title),
  );
};

export const getOverviewSections = ({ services = {}, getLabel, t, shiftTypes = {} } = {}) => {
  const resolveTerm = (key, fallback) =>
    resolveDutyTerm(key, fallback, { getLabel, t, shiftTypes });

  const sections = [];

  if (services?.patrol === true) {
    sections.push({
      id: 'overview-patrol',
      type: 'accordion-section',
      title: `${resolveTerm('patrol', 'Patrol')} Shifts`,
      rows: [],
    });
  }

  if (services?.dedicated === true) {
    sections.push({
      id: 'overview-dedicated',
      type: 'accordion-section',
      title: `${resolveTerm('dedicated', 'Dedicated')} Shifts`,
      rows: [],
    });
  }

  return sections;
};

/** Harmonize acts on visits, so it only exists on the visits tab. */
export const VISITS_SCHEDULE_TAB_ID = 'visits';

export const EMBEDDED_SCHEDULE_TAB_ID = 'embedded';

/** @deprecated Use EMBEDDED_SCHEDULE_TAB_ID */
export const SITE_SCHEDULE_TAB_ID = EMBEDDED_SCHEDULE_TAB_ID;

/** Shared shift-filter option sets. Omit / null on a tab to use DUTIES_FILTER_DATA. */
export const getDedicatedShiftTypeOptions = (t, getLabel, services = {}) => {
  const options = [
    {
      value: 'dedicated',
      label: t('obx.schedules.filters.duties.dedicated', {
        dedicated: getLabel?.('terms', 'dedicated', t) || 'Dedicated',
      }),
    },
    {
      value: 'extra',
      label: t('obx.schedules.filters.duties.extra', {
        extra: getLabel?.('terms', 'extra', t) || 'Extra',
      }),
    },
  ];

  if (services?.dispatch === true) {
    options.push({
      value: 'dispatch',
      label: t('obx.schedules.filters.duties.dispatch', {
        dispatch: getLabel?.('terms', 'dispatch', t) || 'Dispatch',
      }),
    });
  }

  options.push({
    value: 'overtime',
    label: t('obx.schedules.filters.duties.overtime'),
  });

  return options;
};

export const getPatrolShiftTypeOptions = (t, getLabel, services = {}) => {
  const options = [
    {
      value: 'patrol',
      label: t('obx.schedules.filters.duties.patrol', {
        patrol: getLabel?.('terms', 'patrol', t) || 'Patrol',
      }),
    },
  ];

  if (services?.dispatch === true) {
    options.push({
      value: 'dispatch',
      label: t('obx.schedules.filters.duties.dispatch', {
        dispatch: getLabel?.('terms', 'dispatch', t) || 'Dispatch',
      }),
    });
  }

  options.push({
    value: 'overtime',
    label: t('obx.schedules.filters.duties.overtime'),
  });

  return options;
};

/** @deprecated Use getDedicatedShiftTypeOptions */
export const DEDICATED_SHIFT_TYPE_OPTIONS = [
  { value: 'dedicated', label: 'Dedicated Shift' },
  { value: 'extra', label: 'Extra Job' },
  { value: 'dispatch', label: 'Dispatch' },
  { value: 'overtime', label: 'Overtime' },
];

/** @deprecated Use getPatrolShiftTypeOptions */
export const PATROL_SHIFT_TYPE_OPTIONS = [
  { value: 'patrol', label: 'Patrol Shift' },
  { value: 'dispatch', label: 'Dispatch' },
  { value: 'overtime', label: 'Overtime' },
];

export const RESOURCE_AREA_HEADER_KEYS = {
  OFFICERS: 'officers',
  LOCATIONS: 'locations',
  RUNSHEETS: 'runsheets',
  SITES: 'sites',
};

export const resolveResourceAreaHeader = (headerKey, getLabel, t) => {
  if (!headerKey) return '';

  if (headerKey === RESOURCE_AREA_HEADER_KEYS.OFFICERS) {
    return getLabel?.('terms', 'officers', t) || 'Officers';
  }
  if (headerKey === RESOURCE_AREA_HEADER_KEYS.RUNSHEETS) {
    return getLabel?.('terms', 'runsheets', t) || 'Runsheets';
  }
  if (headerKey === RESOURCE_AREA_HEADER_KEYS.LOCATIONS) {
    return t?.('obx.schedules.calendar.resourceHeaders.locations') || 'Locations';
  }
  if (headerKey === RESOURCE_AREA_HEADER_KEYS.SITES) {
    return getLabel?.('terms', 'sites', t) || 'Sites';
  }

  return '';
};

const DEFAULT_FILTERS = {
  showShiftType: true,
  showLocation: true,
  showOfficer: true,
  /** null | 'dedicated' | 'patrol' — resolved at render with getLabel */
  shiftTypeOptionsKey: null,
  patrolStatusOptions: false,
};

export const SCHEDULE_TAB_CONFIGS = {
  embedded: {
    id: EMBEDDED_SCHEDULE_TAB_ID,
    apiView: null,
    footerVariant: null,
    resourceAreaHeaderKey: null,
    isOverviewTab: false,
    isLegacyEmbeddedView: true,
    filters: {
      ...DEFAULT_FILTERS,
      showLocation: false,
      showOfficer: false,
    },
    requiresSiteLocations: false,
  },
  overview: {
    id: 'overview',
    // Week Overview fetches patrol + dedicated grids (no view=overview).
    // Coverage / top-row KPIs come from summary/stats; bottom row sums legends.
    apiView: null,
    footerVariant: SCHEDULE_STATS_FOOTER_VARIANTS.OVERVIEW,
    resourceAreaHeaderKey: null,
    isOverviewTab: true,
    filters: {
      ...DEFAULT_FILTERS,
    },
    requiresSiteLocations: false,
  },
  officer: {
    id: 'officer',
    apiView: 'officer',
    // Tall Overview stats (Coverage + 6 + 9) are Overview-tab only.
    footerVariant: null,
    resourceAreaHeaderKey: RESOURCE_AREA_HEADER_KEYS.OFFICERS,
    isOverviewTab: false,
    filters: {
      ...DEFAULT_FILTERS,
    },
    requiresSiteLocations: false,
  },
  dedicated: {
    id: 'dedicated',
    apiView: 'dedicated',
    footerVariant: SCHEDULE_STATS_FOOTER_VARIANTS.DEDICATED,
    resourceAreaHeaderKey: RESOURCE_AREA_HEADER_KEYS.LOCATIONS,
    isOverviewTab: false,
    filters: {
      ...DEFAULT_FILTERS,
      shiftTypeOptionsKey: 'dedicated',
    },
    requiresSiteLocations: false,
  },
  patrol: {
    id: 'patrol',
    apiView: 'patrol',
    footerVariant: SCHEDULE_STATS_FOOTER_VARIANTS.PATROL,
    resourceAreaHeaderKey: RESOURCE_AREA_HEADER_KEYS.RUNSHEETS,
    isOverviewTab: false,
    filters: {
      ...DEFAULT_FILTERS,
      showLocation: false,
      shiftTypeOptionsKey: 'patrol',
      patrolStatusOptions: true,
    },
    requiresSiteLocations: false,
  },
  /**
   * Visits (API: "hits") are the unit of demand — one service occurrence at one
   * site. Every other week view groups by something a visit must already belong
   * to (a runsheet, a location, an officer), so unassigned demand had no row and
   * could not be drawn at all. Here rows are sites, with unassigned demand
   * pinned above them, which is what makes the whole week visible in one place.
   */
  visits: {
    id: 'visits',
    apiView: 'visits',
    footerVariant: SCHEDULE_STATS_FOOTER_VARIANTS.VISITS,
    resourceAreaHeaderKey: RESOURCE_AREA_HEADER_KEYS.SITES,
    isOverviewTab: false,
    isVisitsTab: true,
    filters: {
      ...DEFAULT_FILTERS,
      showLocation: false,
      shiftTypeOptionsKey: null,
      showShiftType: false,
      patrolStatusOptions: true,
    },
    requiresSiteLocations: false,
  },
};

export const getScheduleTabConfig = (tabId) =>
  SCHEDULE_TAB_CONFIGS[tabId] || SCHEDULE_TAB_CONFIGS.overview;

export const getScheduleTabFooterVariant = (tabId) => getScheduleTabConfig(tabId).footerVariant;
