import { makeStyles } from '@mui/styles';

export const useStyles = makeStyles((theme) => ({
  splitRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '16px',
    width: '100%',
  },
  splitCard: {
    border: `1px solid ${theme.palette.borderSubtle1}`,
    borderRadius: '8px',
    boxSizing: 'border-box',
    cursor: 'pointer',
    textAlign: 'left',
    outline: 'none',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100px',
    '&:hover $splitCardBody': {
      background: theme.palette.action?.hover,
    },
  },
  splitCardHeaderCurrent: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '8px',
    padding: '10px 12px',
    flexShrink: 0,
    backgroundColor: 'rgba(211, 47, 47, 0.08)',
    borderBottom: `1px solid ${theme.palette.borderSubtle1}`,
  },
  splitCardHeaderSuggested: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '8px',
    padding: '10px 12px',
    flexShrink: 0,
    backgroundColor: 'rgba(46, 125, 50, 0.1)',
    borderBottom: `1px solid ${theme.palette.borderSubtle1}`,
  },
  splitCardHeaderLeft: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    minWidth: 0,
    flex: '1 1 auto',
  },
  headerIcon: {
    width: 20,
    height: 20,
    flexShrink: 0,
  },
  currentTitle: {
    color: theme.palette.error?.main,
    fontWeight: 600,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  suggestedTitle: {
    color: theme.palette.success?.main,
    fontWeight: 600,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  fixesPill: {
    display: 'inline-flex',
    alignItems: 'center',
    flexShrink: 0,
    fontSize: 12,
    fontWeight: 600,
    lineHeight: 1.4,
    whiteSpace: 'nowrap',
    borderRadius: 16,
    padding: '2px 10px',
    color: theme.palette.error?.main,
    backgroundColor: 'rgba(211, 47, 47, 0.12)',
    border: '1px solid rgba(211, 47, 47, 0.35)',
  },
  aiPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    flexShrink: 0,
    fontSize: 12,
    fontWeight: 600,
    lineHeight: 1.4,
    whiteSpace: 'nowrap',
    borderRadius: 16,
    padding: '2px 10px',
    color: '#fff',
    background: 'linear-gradient(90deg, #16a34a 0%, #15803d 100%)',
    border: 'none',
    '& svg': {
      width: 14,
      height: 14,
    },
  },
  splitCardBody: {
    padding: '12px 16px',
    flex: '1 1 auto',
    minHeight: 0,
  },
  textBlock: {
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },
  editingHeader: {
    display: 'flex',
    justifyContent: 'flex-end',
    width: '100%',
    marginBottom: '8px',
  },
  reselectBtn: {
    textTransform: 'none',
  },
}));
