/**
 * Demo data for the route builder. Coordinates sit around Tampa, FL to match the
 * rest of the stubbed data in this project.
 *
 * `bucket` is why a visit is a candidate, which is how the pool is grouped:
 *   overdue — missed or left incomplete on an earlier day
 *   today   — due today, whether or not it is already on the live route
 *   ahead   — scheduled later in the week and available to pull forward
 */

export const VISIT_BUCKET = {
  OVERDUE: 'overdue',
  TODAY: 'today',
  AHEAD: 'ahead',
};

/** Start point when the route is live — stands in for the worker's last GPS fix. */
export const CURRENT_POSITION = {
  label: 'Current position',
  address: 'N Florida Ave & E Fowler Ave, Tampa',
  lat: 28.0587,
  lng: -82.4572,
};

export const DEPOT = {
  label: 'Depot',
  address: '4102 W Linebaugh Ave, Tampa, FL',
  lat: 28.0731,
  lng: -82.5121,
};

export const MOCK_VISITS = [
  {
    id: 'v-101',
    siteId: 'site-mill',
    siteName: 'Mill Road Retail',
    unit: 'Unit 1',
    address: '3401 W Mill Rd, Tampa',
    bucket: VISIT_BUCKET.OVERDUE,
    scheduledFor: 'Mon 11 Aug',
    daysOverdue: 1,
    serviceMinutes: 45,
    lat: 28.0402,
    lng: -82.4831,
    filters: [{ name: 'HEPA-12', quantity: 2 }],
    onRunsheet: null,
    withinServiceWindow: true,
  },
  {
    id: 'v-102',
    siteId: 'site-depotst',
    siteName: 'Depot Street Works',
    unit: 'Unit 7',
    address: '1220 Depot St, Tampa',
    bucket: VISIT_BUCKET.OVERDUE,
    scheduledFor: 'Mon 11 Aug',
    daysOverdue: 1,
    serviceMinutes: 30,
    lat: 28.0221,
    lng: -82.4498,
    filters: [{ name: 'Carbon-8', quantity: 3 }],
    onRunsheet: null,
    withinServiceWindow: true,
  },
  {
    id: 'v-103',
    siteId: 'site-harbour',
    siteName: 'Harbour Way Offices',
    unit: 'Unit 3',
    address: '88 Harbour Way, Tampa',
    bucket: VISIT_BUCKET.OVERDUE,
    scheduledFor: 'Fri 08 Aug',
    daysOverdue: 4,
    serviceMinutes: 40,
    lat: 27.9506,
    lng: -82.4572,
    filters: [
      { name: 'HEPA-12', quantity: 1 },
      { name: 'Pre-filter G4', quantity: 4 },
    ],
    onRunsheet: null,
    withinServiceWindow: false,
    windowNote: '4 days past the contracted interval',
  },
  {
    id: 'v-201',
    siteId: 'site-oak',
    siteName: 'Oak Plaza',
    unit: 'Unit 2',
    address: '210 Oak Plaza, Tampa',
    bucket: VISIT_BUCKET.TODAY,
    scheduledFor: 'Tue 12 Aug',
    serviceMinutes: 60,
    lat: 28.0664,
    lng: -82.4291,
    filters: [{ name: 'HEPA-12', quantity: 4 }],
    onRunsheet: 'Tuesday North',
    withinServiceWindow: true,
  },
  {
    id: 'v-202',
    siteId: 'site-oak',
    siteName: 'Oak Plaza',
    unit: 'Unit 6',
    address: '210 Oak Plaza, Tampa',
    bucket: VISIT_BUCKET.TODAY,
    scheduledFor: 'Tue 12 Aug',
    serviceMinutes: 25,
    lat: 28.0664,
    lng: -82.4291,
    filters: [{ name: 'Carbon-8', quantity: 1 }],
    onRunsheet: null,
    withinServiceWindow: true,
  },
  {
    id: 'v-203',
    siteId: 'site-bayside',
    siteName: 'Bayside Clinic',
    unit: 'Unit 4',
    address: '77 Bayshore Blvd, Tampa',
    bucket: VISIT_BUCKET.TODAY,
    scheduledFor: 'Tue 12 Aug',
    serviceMinutes: 50,
    lat: 27.9223,
    lng: -82.4839,
    filters: [
      { name: 'HEPA-12', quantity: 2 },
      { name: 'Carbon-8', quantity: 2 },
    ],
    onRunsheet: 'Tuesday North',
    withinServiceWindow: true,
  },
  {
    id: 'v-204',
    siteId: 'site-crestwood',
    siteName: 'Crestwood Labs',
    unit: 'Unit 5',
    address: '5500 Crestwood Dr, Tampa',
    bucket: VISIT_BUCKET.TODAY,
    scheduledFor: 'Tue 12 Aug',
    serviceMinutes: 35,
    lat: 28.0955,
    lng: -82.4412,
    filters: [{ name: 'Pre-filter G4', quantity: 6 }],
    onRunsheet: null,
    withinServiceWindow: true,
  },
  {
    id: 'v-301',
    siteId: 'site-kiln',
    siteName: 'Kiln Lane Industrial',
    unit: 'Unit 9',
    address: '19 Kiln Ln, Tampa',
    bucket: VISIT_BUCKET.AHEAD,
    scheduledFor: 'Wed 13 Aug',
    daysEarly: 1,
    serviceMinutes: 35,
    lat: 28.0512,
    lng: -82.4104,
    filters: [{ name: 'Carbon-8', quantity: 2 }],
    onRunsheet: 'Wednesday East',
    withinServiceWindow: true,
  },
  {
    id: 'v-302',
    siteId: 'site-fen',
    siteName: 'Fen Court',
    unit: 'Unit 4',
    address: '2 Fen Ct, Tampa',
    bucket: VISIT_BUCKET.AHEAD,
    scheduledFor: 'Thu 14 Aug',
    daysEarly: 2,
    serviceMinutes: 50,
    lat: 28.0138,
    lng: -82.5006,
    filters: [{ name: 'HEPA-12', quantity: 3 }],
    onRunsheet: null,
    withinServiceWindow: true,
  },
  {
    id: 'v-303',
    siteId: 'site-warehouse',
    siteName: 'Northside Warehouse',
    unit: 'Unit 12',
    address: '9001 N 30th St, Tampa',
    bucket: VISIT_BUCKET.AHEAD,
    scheduledFor: 'Thu 14 Aug',
    daysEarly: 2,
    serviceMinutes: 55,
    lat: 28.0341,
    lng: -82.4327,
    filters: [{ name: 'Pre-filter G4', quantity: 8 }],
    onRunsheet: null,
    withinServiceWindow: true,
  },
  {
    id: 'v-304',
    siteId: 'site-riverwalk',
    siteName: 'Riverwalk Hotel',
    unit: 'Unit 2',
    address: '700 Riverwalk, Tampa',
    bucket: VISIT_BUCKET.AHEAD,
    scheduledFor: 'Fri 15 Aug',
    daysEarly: 3,
    serviceMinutes: 45,
    lat: 27.9445,
    lng: -82.461,
    filters: [{ name: 'HEPA-12', quantity: 2 }],
    onRunsheet: null,
    withinServiceWindow: false,
    windowNote: '11 days of filter life would be discarded',
  },
  {
    id: 'v-305',
    siteId: 'site-parkway',
    siteName: 'Parkway Business Centre',
    unit: 'Unit 8',
    address: '1400 Parkway Blvd, Tampa',
    bucket: VISIT_BUCKET.AHEAD,
    scheduledFor: 'Fri 15 Aug',
    daysEarly: 3,
    serviceMinutes: 40,
    lat: 28.0819,
    lng: -82.4738,
    filters: [{ name: 'Carbon-8', quantity: 4 }],
    onRunsheet: null,
    withinServiceWindow: true,
  },
];

/** Runsheets available as merge targets for the selected day. */
export const MOCK_RUNSHEETS = [
  { id: 'rs-1', name: 'Tuesday North', worker: 'Alex Green', stops: 4, status: 'live' },
  { id: 'rs-2', name: 'Tuesday South', worker: 'Alex Green', stops: 3, status: 'notStarted' },
  { id: 'rs-3', name: 'Tuesday Overflow', worker: null, stops: 0, status: 'notStarted' },
];
